{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f4578b83",
   "metadata": {
    "_execution_state": "idle",
    "_uuid": "051d70d956493feee0c6d64651c6a088724dca2a",
    "execution": {
     "iopub.execute_input": "2024-01-18T20:05:24.732271Z",
     "iopub.status.busy": "2024-01-18T20:05:24.730302Z",
     "iopub.status.idle": "2024-01-18T20:05:25.996084Z",
     "shell.execute_reply": "2024-01-18T20:05:25.994434Z"
    },
    "papermill": {
     "duration": 1.273869,
     "end_time": "2024-01-18T20:05:25.998704",
     "exception": false,
     "start_time": "2024-01-18T20:05:24.724835",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "── \u001b[1mAttaching core tidyverse packages\u001b[22m ──────────────────────── tidyverse 2.0.0 ──\n",
      "\u001b[32m✔\u001b[39m \u001b[34mdplyr    \u001b[39m 1.1.4     \u001b[32m✔\u001b[39m \u001b[34mreadr    \u001b[39m 2.1.4\n",
      "\u001b[32m✔\u001b[39m \u001b[34mforcats  \u001b[39m 1.0.0     \u001b[32m✔\u001b[39m \u001b[34mstringr  \u001b[39m 1.5.1\n",
      "\u001b[32m✔\u001b[39m \u001b[34mggplot2  \u001b[39m 3.4.4     \u001b[32m✔\u001b[39m \u001b[34mtibble   \u001b[39m 3.2.1\n",
      "\u001b[32m✔\u001b[39m \u001b[34mlubridate\u001b[39m 1.9.3     \u001b[32m✔\u001b[39m \u001b[34mtidyr    \u001b[39m 1.3.0\n",
      "\u001b[32m✔\u001b[39m \u001b[34mpurrr    \u001b[39m 1.0.2     \n",
      "── \u001b[1mConflicts\u001b[22m ────────────────────────────────────────── tidyverse_conflicts() ──\n",
      "\u001b[31m✖\u001b[39m \u001b[34mdplyr\u001b[39m::\u001b[32mfilter()\u001b[39m masks \u001b[34mstats\u001b[39m::filter()\n",
      "\u001b[31m✖\u001b[39m \u001b[34mdplyr\u001b[39m::\u001b[32mlag()\u001b[39m    masks \u001b[34mstats\u001b[39m::lag()\n",
      "\u001b[36mℹ\u001b[39m Use the conflicted package (\u001b[3m\u001b[34m<http://conflicted.r-lib.org/>\u001b[39m\u001b[23m) to force all conflicts to become errors\n"
     ]
    },
    {
     "data": {
      "text/html": [],
      "text/latex": [],
      "text/markdown": [],
      "text/plain": [
       "character(0)"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# This R environment comes with many helpful analytics packages installed\n",
    "# It is defined by the kaggle/rstats Docker image: https://github.com/kaggle/docker-rstats\n",
    "# For example, here's a helpful package to load\n",
    "\n",
    "library(tidyverse) # metapackage of all tidyverse packages\n",
    "\n",
    "# Input data files are available in the read-only \"../input/\" directory\n",
    "# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory\n",
    "\n",
    "list.files(path = \"/kaggle/input/fatality-analysis-reporting-us-1975-2021/accident.CSV\")\n",
    "\n",
    "# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using \"Save & Run All\" \n",
    "# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "8857fd13",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-01-18T20:05:26.032196Z",
     "iopub.status.busy": "2024-01-18T20:05:26.006564Z",
     "iopub.status.idle": "2024-01-18T20:05:27.388022Z",
     "shell.execute_reply": "2024-01-18T20:05:27.386137Z"
    },
    "papermill": {
     "duration": 1.388685,
     "end_time": "2024-01-18T20:05:27.390491",
     "exception": false,
     "start_time": "2024-01-18T20:05:26.001806",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<table class=\"dataframe\">\n",
       "<caption>A data.frame: 6 × 81</caption>\n",
       "<thead>\n",
       "\t<tr><th></th><th scope=col>STATE</th><th scope=col>STATENAME</th><th scope=col>ST_CASE</th><th scope=col>VE_TOTAL</th><th scope=col>VE_FORMS</th><th scope=col>PVH_INVL</th><th scope=col>PEDS</th><th scope=col>PERSONS</th><th scope=col>PERMVIT</th><th scope=col>PERNOTMVIT</th><th scope=col>⋯</th><th scope=col>ARR_HOUR</th><th scope=col>ARR_HOURNAME</th><th scope=col>ARR_MIN</th><th scope=col>ARR_MINNAME</th><th scope=col>HOSP_HR</th><th scope=col>HOSP_HRNAME</th><th scope=col>HOSP_MN</th><th scope=col>HOSP_MNNAME</th><th scope=col>FATALS</th><th scope=col>DRUNK_DR</th></tr>\n",
       "\t<tr><th></th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>⋯</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;chr&gt;</th><th scope=col>&lt;int&gt;</th><th scope=col>&lt;int&gt;</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "\t<tr><th scope=row>1</th><td>1</td><td>Alabama</td><td>10001</td><td>1</td><td>1</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>⋯</td><td> 3</td><td>3:00am-3:59am                 </td><td>10</td><td>10                               </td><td>99</td><td>Unknown                         </td><td>99</td><td>Unknown EMS Hospital Arrival Time</td><td>3</td><td>1</td></tr>\n",
       "\t<tr><th scope=row>2</th><td>1</td><td>Alabama</td><td>10002</td><td>4</td><td>4</td><td>0</td><td>0</td><td>6</td><td>6</td><td>0</td><td>⋯</td><td>17</td><td>5:00pm-5:59pm                 </td><td>26</td><td>26                               </td><td>99</td><td>Unknown                         </td><td>99</td><td>Unknown EMS Hospital Arrival Time</td><td>1</td><td>0</td></tr>\n",
       "\t<tr><th scope=row>3</th><td>1</td><td>Alabama</td><td>10003</td><td>2</td><td>2</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>⋯</td><td>15</td><td>3:00pm-3:59pm                 </td><td>15</td><td>15                               </td><td>99</td><td>Unknown                         </td><td>99</td><td>Unknown EMS Hospital Arrival Time</td><td>1</td><td>0</td></tr>\n",
       "\t<tr><th scope=row>4</th><td>1</td><td>Alabama</td><td>10004</td><td>1</td><td>1</td><td>0</td><td>0</td><td>5</td><td>5</td><td>0</td><td>⋯</td><td>99</td><td>Unknown EMS Scene Arrival Hour</td><td>99</td><td>Unknown EMS Scene Arrival Minutes</td><td>99</td><td>Unknown                         </td><td>99</td><td>Unknown EMS Hospital Arrival Time</td><td>1</td><td>0</td></tr>\n",
       "\t<tr><th scope=row>5</th><td>1</td><td>Alabama</td><td>10005</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>⋯</td><td> 0</td><td>0:00am-0:59am                 </td><td>55</td><td>55                               </td><td>88</td><td>Not Applicable (Not Transported)</td><td>88</td><td>Not Applicable (Not Transported) </td><td>1</td><td>0</td></tr>\n",
       "\t<tr><th scope=row>6</th><td>1</td><td>Alabama</td><td>10006</td><td>2</td><td>2</td><td>0</td><td>0</td><td>3</td><td>3</td><td>0</td><td>⋯</td><td>17</td><td>5:00pm-5:59pm                 </td><td>19</td><td>19                               </td><td>18</td><td>6:00pm-6:59pm                   </td><td>51</td><td>51                               </td><td>1</td><td>0</td></tr>\n",
       "</tbody>\n",
       "</table>\n"
      ],
      "text/latex": [
       "A data.frame: 6 × 81\n",
       "\\begin{tabular}{r|lllllllllllllllllllll}\n",
       "  & STATE & STATENAME & ST\\_CASE & VE\\_TOTAL & VE\\_FORMS & PVH\\_INVL & PEDS & PERSONS & PERMVIT & PERNOTMVIT & ⋯ & ARR\\_HOUR & ARR\\_HOURNAME & ARR\\_MIN & ARR\\_MINNAME & HOSP\\_HR & HOSP\\_HRNAME & HOSP\\_MN & HOSP\\_MNNAME & FATALS & DRUNK\\_DR\\\\\n",
       "  & <int> & <chr> & <int> & <int> & <int> & <int> & <int> & <int> & <int> & <int> & ⋯ & <int> & <chr> & <int> & <chr> & <int> & <chr> & <int> & <chr> & <int> & <int>\\\\\n",
       "\\hline\n",
       "\t1 & 1 & Alabama & 10001 & 1 & 1 & 0 & 0 & 4 & 4 & 0 & ⋯ &  3 & 3:00am-3:59am                  & 10 & 10                                & 99 & Unknown                          & 99 & Unknown EMS Hospital Arrival Time & 3 & 1\\\\\n",
       "\t2 & 1 & Alabama & 10002 & 4 & 4 & 0 & 0 & 6 & 6 & 0 & ⋯ & 17 & 5:00pm-5:59pm                  & 26 & 26                                & 99 & Unknown                          & 99 & Unknown EMS Hospital Arrival Time & 1 & 0\\\\\n",
       "\t3 & 1 & Alabama & 10003 & 2 & 2 & 0 & 0 & 2 & 2 & 0 & ⋯ & 15 & 3:00pm-3:59pm                  & 15 & 15                                & 99 & Unknown                          & 99 & Unknown EMS Hospital Arrival Time & 1 & 0\\\\\n",
       "\t4 & 1 & Alabama & 10004 & 1 & 1 & 0 & 0 & 5 & 5 & 0 & ⋯ & 99 & Unknown EMS Scene Arrival Hour & 99 & Unknown EMS Scene Arrival Minutes & 99 & Unknown                          & 99 & Unknown EMS Hospital Arrival Time & 1 & 0\\\\\n",
       "\t5 & 1 & Alabama & 10005 & 1 & 1 & 0 & 0 & 1 & 1 & 0 & ⋯ &  0 & 0:00am-0:59am                  & 55 & 55                                & 88 & Not Applicable (Not Transported) & 88 & Not Applicable (Not Transported)  & 1 & 0\\\\\n",
       "\t6 & 1 & Alabama & 10006 & 2 & 2 & 0 & 0 & 3 & 3 & 0 & ⋯ & 17 & 5:00pm-5:59pm                  & 19 & 19                                & 18 & 6:00pm-6:59pm                    & 51 & 51                                & 1 & 0\\\\\n",
       "\\end{tabular}\n"
      ],
      "text/markdown": [
       "\n",
       "A data.frame: 6 × 81\n",
       "\n",
       "| <!--/--> | STATE &lt;int&gt; | STATENAME &lt;chr&gt; | ST_CASE &lt;int&gt; | VE_TOTAL &lt;int&gt; | VE_FORMS &lt;int&gt; | PVH_INVL &lt;int&gt; | PEDS &lt;int&gt; | PERSONS &lt;int&gt; | PERMVIT &lt;int&gt; | PERNOTMVIT &lt;int&gt; | ⋯ ⋯ | ARR_HOUR &lt;int&gt; | ARR_HOURNAME &lt;chr&gt; | ARR_MIN &lt;int&gt; | ARR_MINNAME &lt;chr&gt; | HOSP_HR &lt;int&gt; | HOSP_HRNAME &lt;chr&gt; | HOSP_MN &lt;int&gt; | HOSP_MNNAME &lt;chr&gt; | FATALS &lt;int&gt; | DRUNK_DR &lt;int&gt; |\n",
       "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n",
       "| 1 | 1 | Alabama | 10001 | 1 | 1 | 0 | 0 | 4 | 4 | 0 | ⋯ |  3 | 3:00am-3:59am                  | 10 | 10                                | 99 | Unknown                          | 99 | Unknown EMS Hospital Arrival Time | 3 | 1 |\n",
       "| 2 | 1 | Alabama | 10002 | 4 | 4 | 0 | 0 | 6 | 6 | 0 | ⋯ | 17 | 5:00pm-5:59pm                  | 26 | 26                                | 99 | Unknown                          | 99 | Unknown EMS Hospital Arrival Time | 1 | 0 |\n",
       "| 3 | 1 | Alabama | 10003 | 2 | 2 | 0 | 0 | 2 | 2 | 0 | ⋯ | 15 | 3:00pm-3:59pm                  | 15 | 15                                | 99 | Unknown                          | 99 | Unknown EMS Hospital Arrival Time | 1 | 0 |\n",
       "| 4 | 1 | Alabama | 10004 | 1 | 1 | 0 | 0 | 5 | 5 | 0 | ⋯ | 99 | Unknown EMS Scene Arrival Hour | 99 | Unknown EMS Scene Arrival Minutes | 99 | Unknown                          | 99 | Unknown EMS Hospital Arrival Time | 1 | 0 |\n",
       "| 5 | 1 | Alabama | 10005 | 1 | 1 | 0 | 0 | 1 | 1 | 0 | ⋯ |  0 | 0:00am-0:59am                  | 55 | 55                                | 88 | Not Applicable (Not Transported) | 88 | Not Applicable (Not Transported)  | 1 | 0 |\n",
       "| 6 | 1 | Alabama | 10006 | 2 | 2 | 0 | 0 | 3 | 3 | 0 | ⋯ | 17 | 5:00pm-5:59pm                  | 19 | 19                                | 18 | 6:00pm-6:59pm                    | 51 | 51                                | 1 | 0 |\n",
       "\n"
      ],
      "text/plain": [
       "  STATE STATENAME ST_CASE VE_TOTAL VE_FORMS PVH_INVL PEDS PERSONS PERMVIT\n",
       "1 1     Alabama   10001   1        1        0        0    4       4      \n",
       "2 1     Alabama   10002   4        4        0        0    6       6      \n",
       "3 1     Alabama   10003   2        2        0        0    2       2      \n",
       "4 1     Alabama   10004   1        1        0        0    5       5      \n",
       "5 1     Alabama   10005   1        1        0        0    1       1      \n",
       "6 1     Alabama   10006   2        2        0        0    3       3      \n",
       "  PERNOTMVIT ⋯ ARR_HOUR ARR_HOURNAME                   ARR_MIN\n",
       "1 0          ⋯  3       3:00am-3:59am                  10     \n",
       "2 0          ⋯ 17       5:00pm-5:59pm                  26     \n",
       "3 0          ⋯ 15       3:00pm-3:59pm                  15     \n",
       "4 0          ⋯ 99       Unknown EMS Scene Arrival Hour 99     \n",
       "5 0          ⋯  0       0:00am-0:59am                  55     \n",
       "6 0          ⋯ 17       5:00pm-5:59pm                  19     \n",
       "  ARR_MINNAME                       HOSP_HR HOSP_HRNAME                     \n",
       "1 10                                99      Unknown                         \n",
       "2 26                                99      Unknown                         \n",
       "3 15                                99      Unknown                         \n",
       "4 Unknown EMS Scene Arrival Minutes 99      Unknown                         \n",
       "5 55                                88      Not Applicable (Not Transported)\n",
       "6 19                                18      6:00pm-6:59pm                   \n",
       "  HOSP_MN HOSP_MNNAME                       FATALS DRUNK_DR\n",
       "1 99      Unknown EMS Hospital Arrival Time 3      1       \n",
       "2 99      Unknown EMS Hospital Arrival Time 1      0       \n",
       "3 99      Unknown EMS Hospital Arrival Time 1      0       \n",
       "4 99      Unknown EMS Hospital Arrival Time 1      0       \n",
       "5 88      Not Applicable (Not Transported)  1      0       \n",
       "6 51      51                                1      0       "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "path = '/kaggle/input/fatality-analysis-reporting-us-1975-2021/accident.CSV'\n",
    "accidentData <- read.csv(path, row.names=NULL)\n",
    "head(accidentData)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "0dd7a9ed",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-01-18T20:05:27.400864Z",
     "iopub.status.busy": "2024-01-18T20:05:27.399274Z",
     "iopub.status.idle": "2024-01-18T20:05:27.481464Z",
     "shell.execute_reply": "2024-01-18T20:05:27.479921Z"
    },
    "papermill": {
     "duration": 0.090024,
     "end_time": "2024-01-18T20:05:27.483786",
     "exception": false,
     "start_time": "2024-01-18T20:05:27.393762",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "'data.frame':\t35766 obs. of  81 variables:\n",
      " $ STATE       : int  1 1 1 1 1 1 1 1 1 1 ...\n",
      " $ STATENAME   : chr  \"Alabama\" \"Alabama\" \"Alabama\" \"Alabama\" ...\n",
      " $ ST_CASE     : int  10001 10002 10003 10004 10005 10006 10007 10008 10009 10010 ...\n",
      " $ VE_TOTAL    : int  1 4 2 1 1 2 1 2 2 2 ...\n",
      " $ VE_FORMS    : int  1 4 2 1 1 2 1 2 2 2 ...\n",
      " $ PVH_INVL    : int  0 0 0 0 0 0 0 0 0 0 ...\n",
      " $ PEDS        : int  0 0 0 0 0 0 1 0 0 0 ...\n",
      " $ PERSONS     : int  4 6 2 5 1 3 1 2 4 3 ...\n",
      " $ PERMVIT     : int  4 6 2 5 1 3 1 2 4 3 ...\n",
      " $ PERNOTMVIT  : int  0 0 0 0 0 0 1 0 0 0 ...\n",
      " $ COUNTY      : int  51 73 117 15 37 103 73 25 45 95 ...\n",
      " $ COUNTYNAME  : chr  \"ELMORE (51)\" \"JEFFERSON (73)\" \"SHELBY (117)\" \"CALHOUN (15)\" ...\n",
      " $ CITY        : int  0 350 0 0 0 0 330 0 0 1500 ...\n",
      " $ CITYNAME    : chr  \"NOT APPLICABLE\" \"BIRMINGHAM\" \"NOT APPLICABLE\" \"NOT APPLICABLE\" ...\n",
      " $ DAY         : int  1 2 2 3 4 4 7 8 9 10 ...\n",
      " $ DAYNAME     : int  1 2 2 3 4 4 7 8 9 10 ...\n",
      " $ MONTH       : int  1 1 1 1 1 1 1 1 1 1 ...\n",
      " $ MONTHNAME   : chr  \"January\" \"January\" \"January\" \"January\" ...\n",
      " $ YEAR        : int  2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 ...\n",
      " $ DAY_WEEK    : int  4 5 5 6 7 7 3 4 5 6 ...\n",
      " $ DAY_WEEKNAME: chr  \"Wednesday\" \"Thursday\" \"Thursday\" \"Friday\" ...\n",
      " $ HOUR        : int  2 17 14 15 0 16 19 7 20 10 ...\n",
      " $ HOURNAME    : chr  \"2:00am-2:59am\" \"5:00pm-5:59pm\" \"2:00pm-2:59pm\" \"3:00pm-3:59pm\" ...\n",
      " $ MINUTE      : int  58 18 55 20 45 55 23 15 0 2 ...\n",
      " $ MINUTENAME  : chr  \"58\" \"18\" \"55\" \"20\" ...\n",
      " $ NHS         : int  0 0 0 0 0 0 0 0 0 1 ...\n",
      " $ NHSNAME     : chr  \"This section IS NOT on the NHS\" \"This section IS NOT on the NHS\" \"This section IS NOT on the NHS\" \"This section IS NOT on the NHS\" ...\n",
      " $ ROUTE       : int  4 6 3 4 4 3 4 4 4 2 ...\n",
      " $ ROUTENAME   : chr  \"County Road\" \"Local Street - Municipality\" \"State Highway\" \"County Road\" ...\n",
      " $ TWAY_ID     : chr  \"cr-4\" \"martin luther king jr dr\" \"sr-76\" \"CR-ALEXANDRIA WELLINGTON RD\" ...\n",
      " $ TWAY_ID2    : chr  \"\" \"\" \"us-280\" \"\" ...\n",
      " $ RUR_URB     : int  1 2 1 1 1 1 2 1 1 1 ...\n",
      " $ RUR_URBNAME : chr  \"Rural\" \"Urban\" \"Rural\" \"Rural\" ...\n",
      " $ FUNC_SYS    : int  5 4 4 7 5 4 4 5 5 3 ...\n",
      " $ FUNC_SYSNAME: chr  \"Major Collector\" \"Minor Arterial\" \"Minor Arterial\" \"Local\" ...\n",
      " $ RD_OWNER    : int  2 4 1 2 2 1 4 2 2 1 ...\n",
      " $ RD_OWNERNAME: chr  \"County Highway Agency\" \"City or Municipal Highway Agency\" \"State Highway Agency\" \"County Highway Agency\" ...\n",
      " $ MILEPT      : int  0 0 49 0 0 390 0 0 0 3019 ...\n",
      " $ MILEPTNAME  : chr  \"None\" \"None\" \"49\" \"None\" ...\n",
      " $ LATITUDE    : num  32.4 33.5 33.3 33.8 32.8 ...\n",
      " $ LATITUDENAME: chr  \"32.43313333\" \"33.48465833\" \"33.29994167\" \"33.79507222\" ...\n",
      " $ LONGITUD    : num  -86.1 -86.8 -86.4 -85.9 -86.1 ...\n",
      " $ LONGITUDNAME: chr  \"-86.09485\" \"-86.83954444\" \"-86.36964167\" \"-85.88348611\" ...\n",
      " $ SP_JUR      : int  0 0 0 0 0 0 0 0 0 0 ...\n",
      " $ SP_JURNAME  : chr  \"No Special Jurisdiction\" \"No Special Jurisdiction\" \"No Special Jurisdiction\" \"No Special Jurisdiction\" ...\n",
      " $ HARM_EV     : int  42 12 34 42 42 12 8 12 12 12 ...\n",
      " $ HARM_EVNAME : chr  \"Tree (Standing Only)\" \"Motor Vehicle In-Transport\" \"Ditch\" \"Tree (Standing Only)\" ...\n",
      " $ MAN_COLL    : int  0 6 0 0 0 2 0 1 1 2 ...\n",
      " $ MAN_COLLNAME: chr  \"The First Harmful Event was Not a Collision with a Motor Vehicle in Transport\" \"Angle\" \"The First Harmful Event was Not a Collision with a Motor Vehicle in Transport\" \"The First Harmful Event was Not a Collision with a Motor Vehicle in Transport\" ...\n",
      " $ RELJCT1     : int  0 0 0 0 0 0 0 0 0 0 ...\n",
      " $ RELJCT1NAME : chr  \"No\" \"No\" \"No\" \"No\" ...\n",
      " $ RELJCT2     : int  1 1 3 1 1 1 3 1 8 1 ...\n",
      " $ RELJCT2NAME : chr  \"Non-Junction\" \"Non-Junction\" \"Intersection-Related\" \"Non-Junction\" ...\n",
      " $ TYP_INT     : int  1 1 3 1 1 1 2 1 1 1 ...\n",
      " $ TYP_INTNAME : chr  \"Not an Intersection\" \"Not an Intersection\" \"T-Intersection\" \"Not an Intersection\" ...\n",
      " $ WRK_ZONE    : int  0 0 0 0 0 0 0 0 0 0 ...\n",
      " $ WRK_ZONENAME: chr  \"None\" \"None\" \"None\" \"None\" ...\n",
      " $ REL_ROAD    : int  4 1 4 4 4 1 1 1 1 1 ...\n",
      " $ REL_ROADNAME: chr  \"On Roadside\" \"On Roadway\" \"On Roadside\" \"On Roadside\" ...\n",
      " $ LGT_COND    : int  2 3 1 1 2 2 3 1 2 1 ...\n",
      " $ LGT_CONDNAME: chr  \"Dark - Not Lighted\" \"Dark - Lighted\" \"Daylight\" \"Daylight\" ...\n",
      " $ WEATHER     : int  1 2 2 10 2 1 1 1 10 10 ...\n",
      " $ WEATHERNAME : chr  \"Clear\" \"Rain\" \"Rain\" \"Cloudy\" ...\n",
      " $ SCH_BUS     : int  0 0 0 0 0 0 0 0 0 0 ...\n",
      " $ SCH_BUSNAME : chr  \"No\" \"No\" \"No\" \"No\" ...\n",
      " $ RAIL        : chr  \"0000000\" \"0000000\" \"0000000\" \"0000000\" ...\n",
      " $ RAILNAME    : chr  \"Not Applicable\" \"Not Applicable\" \"Not Applicable\" \"Not Applicable\" ...\n",
      " $ NOT_HOUR    : int  99 17 14 99 0 17 19 7 20 10 ...\n",
      " $ NOT_HOURNAME: chr  \"Unknown\" \"5:00pm-5:59pm\" \"2:00pm-2:59pm\" \"Unknown\" ...\n",
      " $ NOT_MIN     : int  99 18 58 99 45 0 23 21 0 3 ...\n",
      " $ NOT_MINNAME : chr  \"Unknown\" \"18\" \"58\" \"Unknown\" ...\n",
      " $ ARR_HOUR    : int  3 17 15 99 0 17 19 7 20 10 ...\n",
      " $ ARR_HOURNAME: chr  \"3:00am-3:59am\" \"5:00pm-5:59pm\" \"3:00pm-3:59pm\" \"Unknown EMS Scene Arrival Hour\" ...\n",
      " $ ARR_MIN     : int  10 26 15 99 55 19 29 28 10 7 ...\n",
      " $ ARR_MINNAME : chr  \"10\" \"26\" \"15\" \"Unknown EMS Scene Arrival Minutes\" ...\n",
      " $ HOSP_HR     : int  99 99 99 99 88 18 88 88 99 10 ...\n",
      " $ HOSP_HRNAME : chr  \"Unknown\" \"Unknown\" \"Unknown\" \"Unknown\" ...\n",
      " $ HOSP_MN     : int  99 99 99 99 88 51 88 88 99 29 ...\n",
      " $ HOSP_MNNAME : chr  \"Unknown EMS Hospital Arrival Time\" \"Unknown EMS Hospital Arrival Time\" \"Unknown EMS Hospital Arrival Time\" \"Unknown EMS Hospital Arrival Time\" ...\n",
      " $ FATALS      : int  3 1 1 1 1 1 1 1 1 1 ...\n",
      " $ DRUNK_DR    : int  1 0 0 0 0 0 0 0 0 0 ...\n"
     ]
    }
   ],
   "source": [
    "structure = str(accidentData)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "c6f2955d",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-01-18T20:05:27.494306Z",
     "iopub.status.busy": "2024-01-18T20:05:27.492655Z",
     "iopub.status.idle": "2024-01-18T20:05:27.953334Z",
     "shell.execute_reply": "2024-01-18T20:05:27.952013Z"
    },
    "papermill": {
     "duration": 0.468789,
     "end_time": "2024-01-18T20:05:27.955954",
     "exception": false,
     "start_time": "2024-01-18T20:05:27.487165",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1] \"NA\"\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<style>\n",
       ".dl-inline {width: auto; margin:0; padding: 0}\n",
       ".dl-inline>dt, .dl-inline>dd {float: none; width: auto; display: inline-block}\n",
       ".dl-inline>dt::after {content: \":\\0020\"; padding-right: .5ex}\n",
       ".dl-inline>dt:not(:first-of-type) {padding-left: .5ex}\n",
       "</style><dl class=dl-inline><dt>STATE</dt><dd>0</dd><dt>STATENAME</dt><dd>0</dd><dt>ST_CASE</dt><dd>0</dd><dt>VE_TOTAL</dt><dd>0</dd><dt>VE_FORMS</dt><dd>0</dd><dt>PVH_INVL</dt><dd>0</dd><dt>PEDS</dt><dd>0</dd><dt>PERSONS</dt><dd>0</dd><dt>PERMVIT</dt><dd>0</dd><dt>PERNOTMVIT</dt><dd>0</dd><dt>COUNTY</dt><dd>0</dd><dt>COUNTYNAME</dt><dd>0</dd><dt>CITY</dt><dd>0</dd><dt>CITYNAME</dt><dd>0</dd><dt>DAY</dt><dd>0</dd><dt>DAYNAME</dt><dd>0</dd><dt>MONTH</dt><dd>0</dd><dt>MONTHNAME</dt><dd>0</dd><dt>YEAR</dt><dd>0</dd><dt>DAY_WEEK</dt><dd>0</dd><dt>DAY_WEEKNAME</dt><dd>0</dd><dt>HOUR</dt><dd>0</dd><dt>HOURNAME</dt><dd>0</dd><dt>MINUTE</dt><dd>0</dd><dt>MINUTENAME</dt><dd>0</dd><dt>NHS</dt><dd>0</dd><dt>NHSNAME</dt><dd>0</dd><dt>ROUTE</dt><dd>0</dd><dt>ROUTENAME</dt><dd>0</dd><dt>TWAY_ID</dt><dd>0</dd><dt>TWAY_ID2</dt><dd>0</dd><dt>RUR_URB</dt><dd>0</dd><dt>RUR_URBNAME</dt><dd>0</dd><dt>FUNC_SYS</dt><dd>0</dd><dt>FUNC_SYSNAME</dt><dd>0</dd><dt>RD_OWNER</dt><dd>0</dd><dt>RD_OWNERNAME</dt><dd>0</dd><dt>MILEPT</dt><dd>0</dd><dt>MILEPTNAME</dt><dd>0</dd><dt>LATITUDE</dt><dd>0</dd><dt>LATITUDENAME</dt><dd>0</dd><dt>LONGITUD</dt><dd>0</dd><dt>LONGITUDNAME</dt><dd>0</dd><dt>SP_JUR</dt><dd>0</dd><dt>SP_JURNAME</dt><dd>0</dd><dt>HARM_EV</dt><dd>0</dd><dt>HARM_EVNAME</dt><dd>0</dd><dt>MAN_COLL</dt><dd>0</dd><dt>MAN_COLLNAME</dt><dd>0</dd><dt>RELJCT1</dt><dd>0</dd><dt>RELJCT1NAME</dt><dd>0</dd><dt>RELJCT2</dt><dd>0</dd><dt>RELJCT2NAME</dt><dd>0</dd><dt>TYP_INT</dt><dd>0</dd><dt>TYP_INTNAME</dt><dd>0</dd><dt>WRK_ZONE</dt><dd>0</dd><dt>WRK_ZONENAME</dt><dd>0</dd><dt>REL_ROAD</dt><dd>0</dd><dt>REL_ROADNAME</dt><dd>0</dd><dt>LGT_COND</dt><dd>0</dd><dt>LGT_CONDNAME</dt><dd>0</dd><dt>WEATHER</dt><dd>0</dd><dt>WEATHERNAME</dt><dd>0</dd><dt>SCH_BUS</dt><dd>0</dd><dt>SCH_BUSNAME</dt><dd>0</dd><dt>RAIL</dt><dd>0</dd><dt>RAILNAME</dt><dd>0</dd><dt>NOT_HOUR</dt><dd>0</dd><dt>NOT_HOURNAME</dt><dd>0</dd><dt>NOT_MIN</dt><dd>0</dd><dt>NOT_MINNAME</dt><dd>0</dd><dt>ARR_HOUR</dt><dd>0</dd><dt>ARR_HOURNAME</dt><dd>0</dd><dt>ARR_MIN</dt><dd>0</dd><dt>ARR_MINNAME</dt><dd>0</dd><dt>HOSP_HR</dt><dd>0</dd><dt>HOSP_HRNAME</dt><dd>0</dd><dt>HOSP_MN</dt><dd>0</dd><dt>HOSP_MNNAME</dt><dd>0</dd><dt>FATALS</dt><dd>0</dd><dt>DRUNK_DR</dt><dd>0</dd></dl>\n"
      ],
      "text/latex": [
       "\\begin{description*}\n",
       "\\item[STATE] 0\n",
       "\\item[STATENAME] 0\n",
       "\\item[ST\\textbackslash{}\\_CASE] 0\n",
       "\\item[VE\\textbackslash{}\\_TOTAL] 0\n",
       "\\item[VE\\textbackslash{}\\_FORMS] 0\n",
       "\\item[PVH\\textbackslash{}\\_INVL] 0\n",
       "\\item[PEDS] 0\n",
       "\\item[PERSONS] 0\n",
       "\\item[PERMVIT] 0\n",
       "\\item[PERNOTMVIT] 0\n",
       "\\item[COUNTY] 0\n",
       "\\item[COUNTYNAME] 0\n",
       "\\item[CITY] 0\n",
       "\\item[CITYNAME] 0\n",
       "\\item[DAY] 0\n",
       "\\item[DAYNAME] 0\n",
       "\\item[MONTH] 0\n",
       "\\item[MONTHNAME] 0\n",
       "\\item[YEAR] 0\n",
       "\\item[DAY\\textbackslash{}\\_WEEK] 0\n",
       "\\item[DAY\\textbackslash{}\\_WEEKNAME] 0\n",
       "\\item[HOUR] 0\n",
       "\\item[HOURNAME] 0\n",
       "\\item[MINUTE] 0\n",
       "\\item[MINUTENAME] 0\n",
       "\\item[NHS] 0\n",
       "\\item[NHSNAME] 0\n",
       "\\item[ROUTE] 0\n",
       "\\item[ROUTENAME] 0\n",
       "\\item[TWAY\\textbackslash{}\\_ID] 0\n",
       "\\item[TWAY\\textbackslash{}\\_ID2] 0\n",
       "\\item[RUR\\textbackslash{}\\_URB] 0\n",
       "\\item[RUR\\textbackslash{}\\_URBNAME] 0\n",
       "\\item[FUNC\\textbackslash{}\\_SYS] 0\n",
       "\\item[FUNC\\textbackslash{}\\_SYSNAME] 0\n",
       "\\item[RD\\textbackslash{}\\_OWNER] 0\n",
       "\\item[RD\\textbackslash{}\\_OWNERNAME] 0\n",
       "\\item[MILEPT] 0\n",
       "\\item[MILEPTNAME] 0\n",
       "\\item[LATITUDE] 0\n",
       "\\item[LATITUDENAME] 0\n",
       "\\item[LONGITUD] 0\n",
       "\\item[LONGITUDNAME] 0\n",
       "\\item[SP\\textbackslash{}\\_JUR] 0\n",
       "\\item[SP\\textbackslash{}\\_JURNAME] 0\n",
       "\\item[HARM\\textbackslash{}\\_EV] 0\n",
       "\\item[HARM\\textbackslash{}\\_EVNAME] 0\n",
       "\\item[MAN\\textbackslash{}\\_COLL] 0\n",
       "\\item[MAN\\textbackslash{}\\_COLLNAME] 0\n",
       "\\item[RELJCT1] 0\n",
       "\\item[RELJCT1NAME] 0\n",
       "\\item[RELJCT2] 0\n",
       "\\item[RELJCT2NAME] 0\n",
       "\\item[TYP\\textbackslash{}\\_INT] 0\n",
       "\\item[TYP\\textbackslash{}\\_INTNAME] 0\n",
       "\\item[WRK\\textbackslash{}\\_ZONE] 0\n",
       "\\item[WRK\\textbackslash{}\\_ZONENAME] 0\n",
       "\\item[REL\\textbackslash{}\\_ROAD] 0\n",
       "\\item[REL\\textbackslash{}\\_ROADNAME] 0\n",
       "\\item[LGT\\textbackslash{}\\_COND] 0\n",
       "\\item[LGT\\textbackslash{}\\_CONDNAME] 0\n",
       "\\item[WEATHER] 0\n",
       "\\item[WEATHERNAME] 0\n",
       "\\item[SCH\\textbackslash{}\\_BUS] 0\n",
       "\\item[SCH\\textbackslash{}\\_BUSNAME] 0\n",
       "\\item[RAIL] 0\n",
       "\\item[RAILNAME] 0\n",
       "\\item[NOT\\textbackslash{}\\_HOUR] 0\n",
       "\\item[NOT\\textbackslash{}\\_HOURNAME] 0\n",
       "\\item[NOT\\textbackslash{}\\_MIN] 0\n",
       "\\item[NOT\\textbackslash{}\\_MINNAME] 0\n",
       "\\item[ARR\\textbackslash{}\\_HOUR] 0\n",
       "\\item[ARR\\textbackslash{}\\_HOURNAME] 0\n",
       "\\item[ARR\\textbackslash{}\\_MIN] 0\n",
       "\\item[ARR\\textbackslash{}\\_MINNAME] 0\n",
       "\\item[HOSP\\textbackslash{}\\_HR] 0\n",
       "\\item[HOSP\\textbackslash{}\\_HRNAME] 0\n",
       "\\item[HOSP\\textbackslash{}\\_MN] 0\n",
       "\\item[HOSP\\textbackslash{}\\_MNNAME] 0\n",
       "\\item[FATALS] 0\n",
       "\\item[DRUNK\\textbackslash{}\\_DR] 0\n",
       "\\end{description*}\n"
      ],
      "text/markdown": [
       "STATE\n",
       ":   0STATENAME\n",
       ":   0ST_CASE\n",
       ":   0VE_TOTAL\n",
       ":   0VE_FORMS\n",
       ":   0PVH_INVL\n",
       ":   0PEDS\n",
       ":   0PERSONS\n",
       ":   0PERMVIT\n",
       ":   0PERNOTMVIT\n",
       ":   0COUNTY\n",
       ":   0COUNTYNAME\n",
       ":   0CITY\n",
       ":   0CITYNAME\n",
       ":   0DAY\n",
       ":   0DAYNAME\n",
       ":   0MONTH\n",
       ":   0MONTHNAME\n",
       ":   0YEAR\n",
       ":   0DAY_WEEK\n",
       ":   0DAY_WEEKNAME\n",
       ":   0HOUR\n",
       ":   0HOURNAME\n",
       ":   0MINUTE\n",
       ":   0MINUTENAME\n",
       ":   0NHS\n",
       ":   0NHSNAME\n",
       ":   0ROUTE\n",
       ":   0ROUTENAME\n",
       ":   0TWAY_ID\n",
       ":   0TWAY_ID2\n",
       ":   0RUR_URB\n",
       ":   0RUR_URBNAME\n",
       ":   0FUNC_SYS\n",
       ":   0FUNC_SYSNAME\n",
       ":   0RD_OWNER\n",
       ":   0RD_OWNERNAME\n",
       ":   0MILEPT\n",
       ":   0MILEPTNAME\n",
       ":   0LATITUDE\n",
       ":   0LATITUDENAME\n",
       ":   0LONGITUD\n",
       ":   0LONGITUDNAME\n",
       ":   0SP_JUR\n",
       ":   0SP_JURNAME\n",
       ":   0HARM_EV\n",
       ":   0HARM_EVNAME\n",
       ":   0MAN_COLL\n",
       ":   0MAN_COLLNAME\n",
       ":   0RELJCT1\n",
       ":   0RELJCT1NAME\n",
       ":   0RELJCT2\n",
       ":   0RELJCT2NAME\n",
       ":   0TYP_INT\n",
       ":   0TYP_INTNAME\n",
       ":   0WRK_ZONE\n",
       ":   0WRK_ZONENAME\n",
       ":   0REL_ROAD\n",
       ":   0REL_ROADNAME\n",
       ":   0LGT_COND\n",
       ":   0LGT_CONDNAME\n",
       ":   0WEATHER\n",
       ":   0WEATHERNAME\n",
       ":   0SCH_BUS\n",
       ":   0SCH_BUSNAME\n",
       ":   0RAIL\n",
       ":   0RAILNAME\n",
       ":   0NOT_HOUR\n",
       ":   0NOT_HOURNAME\n",
       ":   0NOT_MIN\n",
       ":   0NOT_MINNAME\n",
       ":   0ARR_HOUR\n",
       ":   0ARR_HOURNAME\n",
       ":   0ARR_MIN\n",
       ":   0ARR_MINNAME\n",
       ":   0HOSP_HR\n",
       ":   0HOSP_HRNAME\n",
       ":   0HOSP_MN\n",
       ":   0HOSP_MNNAME\n",
       ":   0FATALS\n",
       ":   0DRUNK_DR\n",
       ":   0\n",
       "\n"
      ],
      "text/plain": [
       "       STATE    STATENAME      ST_CASE     VE_TOTAL     VE_FORMS     PVH_INVL \n",
       "           0            0            0            0            0            0 \n",
       "        PEDS      PERSONS      PERMVIT   PERNOTMVIT       COUNTY   COUNTYNAME \n",
       "           0            0            0            0            0            0 \n",
       "        CITY     CITYNAME          DAY      DAYNAME        MONTH    MONTHNAME \n",
       "           0            0            0            0            0            0 \n",
       "        YEAR     DAY_WEEK DAY_WEEKNAME         HOUR     HOURNAME       MINUTE \n",
       "           0            0            0            0            0            0 \n",
       "  MINUTENAME          NHS      NHSNAME        ROUTE    ROUTENAME      TWAY_ID \n",
       "           0            0            0            0            0            0 \n",
       "    TWAY_ID2      RUR_URB  RUR_URBNAME     FUNC_SYS FUNC_SYSNAME     RD_OWNER \n",
       "           0            0            0            0            0            0 \n",
       "RD_OWNERNAME       MILEPT   MILEPTNAME     LATITUDE LATITUDENAME     LONGITUD \n",
       "           0            0            0            0            0            0 \n",
       "LONGITUDNAME       SP_JUR   SP_JURNAME      HARM_EV  HARM_EVNAME     MAN_COLL \n",
       "           0            0            0            0            0            0 \n",
       "MAN_COLLNAME      RELJCT1  RELJCT1NAME      RELJCT2  RELJCT2NAME      TYP_INT \n",
       "           0            0            0            0            0            0 \n",
       " TYP_INTNAME     WRK_ZONE WRK_ZONENAME     REL_ROAD REL_ROADNAME     LGT_COND \n",
       "           0            0            0            0            0            0 \n",
       "LGT_CONDNAME      WEATHER  WEATHERNAME      SCH_BUS  SCH_BUSNAME         RAIL \n",
       "           0            0            0            0            0            0 \n",
       "    RAILNAME     NOT_HOUR NOT_HOURNAME      NOT_MIN  NOT_MINNAME     ARR_HOUR \n",
       "           0            0            0            0            0            0 \n",
       "ARR_HOURNAME      ARR_MIN  ARR_MINNAME      HOSP_HR  HOSP_HRNAME      HOSP_MN \n",
       "           0            0            0            0            0            0 \n",
       " HOSP_MNNAME       FATALS     DRUNK_DR \n",
       "           0            0            0 "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<style>\n",
       ".dl-inline {width: auto; margin:0; padding: 0}\n",
       ".dl-inline>dt, .dl-inline>dd {float: none; width: auto; display: inline-block}\n",
       ".dl-inline>dt::after {content: \":\\0020\"; padding-right: .5ex}\n",
       ".dl-inline>dt:not(:first-of-type) {padding-left: .5ex}\n",
       "</style><dl class=dl-inline><dt>STATE</dt><dd>0</dd><dt>STATENAME</dt><dd>0</dd><dt>ST_CASE</dt><dd>0</dd><dt>VE_TOTAL</dt><dd>0</dd><dt>VE_FORMS</dt><dd>0</dd><dt>PVH_INVL</dt><dd>0</dd><dt>PEDS</dt><dd>0</dd><dt>PERSONS</dt><dd>0</dd><dt>PERMVIT</dt><dd>0</dd><dt>PERNOTMVIT</dt><dd>0</dd><dt>COUNTY</dt><dd>0</dd><dt>COUNTYNAME</dt><dd>0</dd><dt>CITY</dt><dd>0</dd><dt>CITYNAME</dt><dd>0</dd><dt>DAY</dt><dd>0</dd><dt>DAYNAME</dt><dd>0</dd><dt>MONTH</dt><dd>0</dd><dt>MONTHNAME</dt><dd>0</dd><dt>YEAR</dt><dd>0</dd><dt>DAY_WEEK</dt><dd>0</dd><dt>DAY_WEEKNAME</dt><dd>0</dd><dt>HOUR</dt><dd>0</dd><dt>HOURNAME</dt><dd>0</dd><dt>MINUTE</dt><dd>0</dd><dt>MINUTENAME</dt><dd>0</dd><dt>NHS</dt><dd>0</dd><dt>NHSNAME</dt><dd>0</dd><dt>ROUTE</dt><dd>0</dd><dt>ROUTENAME</dt><dd>0</dd><dt>TWAY_ID</dt><dd>0</dd><dt>TWAY_ID2</dt><dd>26997</dd><dt>RUR_URB</dt><dd>0</dd><dt>RUR_URBNAME</dt><dd>0</dd><dt>FUNC_SYS</dt><dd>0</dd><dt>FUNC_SYSNAME</dt><dd>0</dd><dt>RD_OWNER</dt><dd>0</dd><dt>RD_OWNERNAME</dt><dd>0</dd><dt>MILEPT</dt><dd>0</dd><dt>MILEPTNAME</dt><dd>0</dd><dt>LATITUDE</dt><dd>0</dd><dt>LATITUDENAME</dt><dd>0</dd><dt>LONGITUD</dt><dd>0</dd><dt>LONGITUDNAME</dt><dd>0</dd><dt>SP_JUR</dt><dd>0</dd><dt>SP_JURNAME</dt><dd>0</dd><dt>HARM_EV</dt><dd>0</dd><dt>HARM_EVNAME</dt><dd>0</dd><dt>MAN_COLL</dt><dd>0</dd><dt>MAN_COLLNAME</dt><dd>0</dd><dt>RELJCT1</dt><dd>0</dd><dt>RELJCT1NAME</dt><dd>0</dd><dt>RELJCT2</dt><dd>0</dd><dt>RELJCT2NAME</dt><dd>0</dd><dt>TYP_INT</dt><dd>0</dd><dt>TYP_INTNAME</dt><dd>0</dd><dt>WRK_ZONE</dt><dd>0</dd><dt>WRK_ZONENAME</dt><dd>0</dd><dt>REL_ROAD</dt><dd>0</dd><dt>REL_ROADNAME</dt><dd>0</dd><dt>LGT_COND</dt><dd>0</dd><dt>LGT_CONDNAME</dt><dd>0</dd><dt>WEATHER</dt><dd>0</dd><dt>WEATHERNAME</dt><dd>0</dd><dt>SCH_BUS</dt><dd>0</dd><dt>SCH_BUSNAME</dt><dd>0</dd><dt>RAIL</dt><dd>0</dd><dt>RAILNAME</dt><dd>0</dd><dt>NOT_HOUR</dt><dd>0</dd><dt>NOT_HOURNAME</dt><dd>0</dd><dt>NOT_MIN</dt><dd>0</dd><dt>NOT_MINNAME</dt><dd>0</dd><dt>ARR_HOUR</dt><dd>0</dd><dt>ARR_HOURNAME</dt><dd>0</dd><dt>ARR_MIN</dt><dd>0</dd><dt>ARR_MINNAME</dt><dd>0</dd><dt>HOSP_HR</dt><dd>0</dd><dt>HOSP_HRNAME</dt><dd>0</dd><dt>HOSP_MN</dt><dd>0</dd><dt>HOSP_MNNAME</dt><dd>0</dd><dt>FATALS</dt><dd>0</dd><dt>DRUNK_DR</dt><dd>0</dd></dl>\n"
      ],
      "text/latex": [
       "\\begin{description*}\n",
       "\\item[STATE] 0\n",
       "\\item[STATENAME] 0\n",
       "\\item[ST\\textbackslash{}\\_CASE] 0\n",
       "\\item[VE\\textbackslash{}\\_TOTAL] 0\n",
       "\\item[VE\\textbackslash{}\\_FORMS] 0\n",
       "\\item[PVH\\textbackslash{}\\_INVL] 0\n",
       "\\item[PEDS] 0\n",
       "\\item[PERSONS] 0\n",
       "\\item[PERMVIT] 0\n",
       "\\item[PERNOTMVIT] 0\n",
       "\\item[COUNTY] 0\n",
       "\\item[COUNTYNAME] 0\n",
       "\\item[CITY] 0\n",
       "\\item[CITYNAME] 0\n",
       "\\item[DAY] 0\n",
       "\\item[DAYNAME] 0\n",
       "\\item[MONTH] 0\n",
       "\\item[MONTHNAME] 0\n",
       "\\item[YEAR] 0\n",
       "\\item[DAY\\textbackslash{}\\_WEEK] 0\n",
       "\\item[DAY\\textbackslash{}\\_WEEKNAME] 0\n",
       "\\item[HOUR] 0\n",
       "\\item[HOURNAME] 0\n",
       "\\item[MINUTE] 0\n",
       "\\item[MINUTENAME] 0\n",
       "\\item[NHS] 0\n",
       "\\item[NHSNAME] 0\n",
       "\\item[ROUTE] 0\n",
       "\\item[ROUTENAME] 0\n",
       "\\item[TWAY\\textbackslash{}\\_ID] 0\n",
       "\\item[TWAY\\textbackslash{}\\_ID2] 26997\n",
       "\\item[RUR\\textbackslash{}\\_URB] 0\n",
       "\\item[RUR\\textbackslash{}\\_URBNAME] 0\n",
       "\\item[FUNC\\textbackslash{}\\_SYS] 0\n",
       "\\item[FUNC\\textbackslash{}\\_SYSNAME] 0\n",
       "\\item[RD\\textbackslash{}\\_OWNER] 0\n",
       "\\item[RD\\textbackslash{}\\_OWNERNAME] 0\n",
       "\\item[MILEPT] 0\n",
       "\\item[MILEPTNAME] 0\n",
       "\\item[LATITUDE] 0\n",
       "\\item[LATITUDENAME] 0\n",
       "\\item[LONGITUD] 0\n",
       "\\item[LONGITUDNAME] 0\n",
       "\\item[SP\\textbackslash{}\\_JUR] 0\n",
       "\\item[SP\\textbackslash{}\\_JURNAME] 0\n",
       "\\item[HARM\\textbackslash{}\\_EV] 0\n",
       "\\item[HARM\\textbackslash{}\\_EVNAME] 0\n",
       "\\item[MAN\\textbackslash{}\\_COLL] 0\n",
       "\\item[MAN\\textbackslash{}\\_COLLNAME] 0\n",
       "\\item[RELJCT1] 0\n",
       "\\item[RELJCT1NAME] 0\n",
       "\\item[RELJCT2] 0\n",
       "\\item[RELJCT2NAME] 0\n",
       "\\item[TYP\\textbackslash{}\\_INT] 0\n",
       "\\item[TYP\\textbackslash{}\\_INTNAME] 0\n",
       "\\item[WRK\\textbackslash{}\\_ZONE] 0\n",
       "\\item[WRK\\textbackslash{}\\_ZONENAME] 0\n",
       "\\item[REL\\textbackslash{}\\_ROAD] 0\n",
       "\\item[REL\\textbackslash{}\\_ROADNAME] 0\n",
       "\\item[LGT\\textbackslash{}\\_COND] 0\n",
       "\\item[LGT\\textbackslash{}\\_CONDNAME] 0\n",
       "\\item[WEATHER] 0\n",
       "\\item[WEATHERNAME] 0\n",
       "\\item[SCH\\textbackslash{}\\_BUS] 0\n",
       "\\item[SCH\\textbackslash{}\\_BUSNAME] 0\n",
       "\\item[RAIL] 0\n",
       "\\item[RAILNAME] 0\n",
       "\\item[NOT\\textbackslash{}\\_HOUR] 0\n",
       "\\item[NOT\\textbackslash{}\\_HOURNAME] 0\n",
       "\\item[NOT\\textbackslash{}\\_MIN] 0\n",
       "\\item[NOT\\textbackslash{}\\_MINNAME] 0\n",
       "\\item[ARR\\textbackslash{}\\_HOUR] 0\n",
       "\\item[ARR\\textbackslash{}\\_HOURNAME] 0\n",
       "\\item[ARR\\textbackslash{}\\_MIN] 0\n",
       "\\item[ARR\\textbackslash{}\\_MINNAME] 0\n",
       "\\item[HOSP\\textbackslash{}\\_HR] 0\n",
       "\\item[HOSP\\textbackslash{}\\_HRNAME] 0\n",
       "\\item[HOSP\\textbackslash{}\\_MN] 0\n",
       "\\item[HOSP\\textbackslash{}\\_MNNAME] 0\n",
       "\\item[FATALS] 0\n",
       "\\item[DRUNK\\textbackslash{}\\_DR] 0\n",
       "\\end{description*}\n"
      ],
      "text/markdown": [
       "STATE\n",
       ":   0STATENAME\n",
       ":   0ST_CASE\n",
       ":   0VE_TOTAL\n",
       ":   0VE_FORMS\n",
       ":   0PVH_INVL\n",
       ":   0PEDS\n",
       ":   0PERSONS\n",
       ":   0PERMVIT\n",
       ":   0PERNOTMVIT\n",
       ":   0COUNTY\n",
       ":   0COUNTYNAME\n",
       ":   0CITY\n",
       ":   0CITYNAME\n",
       ":   0DAY\n",
       ":   0DAYNAME\n",
       ":   0MONTH\n",
       ":   0MONTHNAME\n",
       ":   0YEAR\n",
       ":   0DAY_WEEK\n",
       ":   0DAY_WEEKNAME\n",
       ":   0HOUR\n",
       ":   0HOURNAME\n",
       ":   0MINUTE\n",
       ":   0MINUTENAME\n",
       ":   0NHS\n",
       ":   0NHSNAME\n",
       ":   0ROUTE\n",
       ":   0ROUTENAME\n",
       ":   0TWAY_ID\n",
       ":   0TWAY_ID2\n",
       ":   26997RUR_URB\n",
       ":   0RUR_URBNAME\n",
       ":   0FUNC_SYS\n",
       ":   0FUNC_SYSNAME\n",
       ":   0RD_OWNER\n",
       ":   0RD_OWNERNAME\n",
       ":   0MILEPT\n",
       ":   0MILEPTNAME\n",
       ":   0LATITUDE\n",
       ":   0LATITUDENAME\n",
       ":   0LONGITUD\n",
       ":   0LONGITUDNAME\n",
       ":   0SP_JUR\n",
       ":   0SP_JURNAME\n",
       ":   0HARM_EV\n",
       ":   0HARM_EVNAME\n",
       ":   0MAN_COLL\n",
       ":   0MAN_COLLNAME\n",
       ":   0RELJCT1\n",
       ":   0RELJCT1NAME\n",
       ":   0RELJCT2\n",
       ":   0RELJCT2NAME\n",
       ":   0TYP_INT\n",
       ":   0TYP_INTNAME\n",
       ":   0WRK_ZONE\n",
       ":   0WRK_ZONENAME\n",
       ":   0REL_ROAD\n",
       ":   0REL_ROADNAME\n",
       ":   0LGT_COND\n",
       ":   0LGT_CONDNAME\n",
       ":   0WEATHER\n",
       ":   0WEATHERNAME\n",
       ":   0SCH_BUS\n",
       ":   0SCH_BUSNAME\n",
       ":   0RAIL\n",
       ":   0RAILNAME\n",
       ":   0NOT_HOUR\n",
       ":   0NOT_HOURNAME\n",
       ":   0NOT_MIN\n",
       ":   0NOT_MINNAME\n",
       ":   0ARR_HOUR\n",
       ":   0ARR_HOURNAME\n",
       ":   0ARR_MIN\n",
       ":   0ARR_MINNAME\n",
       ":   0HOSP_HR\n",
       ":   0HOSP_HRNAME\n",
       ":   0HOSP_MN\n",
       ":   0HOSP_MNNAME\n",
       ":   0FATALS\n",
       ":   0DRUNK_DR\n",
       ":   0\n",
       "\n"
      ],
      "text/plain": [
       "       STATE    STATENAME      ST_CASE     VE_TOTAL     VE_FORMS     PVH_INVL \n",
       "           0            0            0            0            0            0 \n",
       "        PEDS      PERSONS      PERMVIT   PERNOTMVIT       COUNTY   COUNTYNAME \n",
       "           0            0            0            0            0            0 \n",
       "        CITY     CITYNAME          DAY      DAYNAME        MONTH    MONTHNAME \n",
       "           0            0            0            0            0            0 \n",
       "        YEAR     DAY_WEEK DAY_WEEKNAME         HOUR     HOURNAME       MINUTE \n",
       "           0            0            0            0            0            0 \n",
       "  MINUTENAME          NHS      NHSNAME        ROUTE    ROUTENAME      TWAY_ID \n",
       "           0            0            0            0            0            0 \n",
       "    TWAY_ID2      RUR_URB  RUR_URBNAME     FUNC_SYS FUNC_SYSNAME     RD_OWNER \n",
       "       26997            0            0            0            0            0 \n",
       "RD_OWNERNAME       MILEPT   MILEPTNAME     LATITUDE LATITUDENAME     LONGITUD \n",
       "           0            0            0            0            0            0 \n",
       "LONGITUDNAME       SP_JUR   SP_JURNAME      HARM_EV  HARM_EVNAME     MAN_COLL \n",
       "           0            0            0            0            0            0 \n",
       "MAN_COLLNAME      RELJCT1  RELJCT1NAME      RELJCT2  RELJCT2NAME      TYP_INT \n",
       "           0            0            0            0            0            0 \n",
       " TYP_INTNAME     WRK_ZONE WRK_ZONENAME     REL_ROAD REL_ROADNAME     LGT_COND \n",
       "           0            0            0            0            0            0 \n",
       "LGT_CONDNAME      WEATHER  WEATHERNAME      SCH_BUS  SCH_BUSNAME         RAIL \n",
       "           0            0            0            0            0            0 \n",
       "    RAILNAME     NOT_HOUR NOT_HOURNAME      NOT_MIN  NOT_MINNAME     ARR_HOUR \n",
       "           0            0            0            0            0            0 \n",
       "ARR_HOURNAME      ARR_MIN  ARR_MINNAME      HOSP_HR  HOSP_HRNAME      HOSP_MN \n",
       "           0            0            0            0            0            0 \n",
       " HOSP_MNNAME       FATALS     DRUNK_DR \n",
       "           0            0            0 "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "print('NA')\n",
    "colSums(is.na(accidentData))\n",
    "colSums(accidentData==\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "13ebede6",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-01-18T20:05:27.967597Z",
     "iopub.status.busy": "2024-01-18T20:05:27.966081Z",
     "iopub.status.idle": "2024-01-18T20:05:42.654009Z",
     "shell.execute_reply": "2024-01-18T20:05:42.651941Z"
    },
    "papermill": {
     "duration": 14.696872,
     "end_time": "2024-01-18T20:05:42.656928",
     "exception": false,
     "start_time": "2024-01-18T20:05:27.960056",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Loading required package: Rmisc\n",
      "\n",
      "Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :\n",
      "“there is no package called ‘Rmisc’”\n",
      "Installing package into ‘/usr/local/lib/R/site-library’\n",
      "(as ‘lib’ is unspecified)\n",
      "\n",
      "Loading required package: lattice\n",
      "\n",
      "Loading required package: plyr\n",
      "\n",
      "------------------------------------------------------------------------------\n",
      "\n",
      "You have loaded plyr after dplyr - this is likely to cause problems.\n",
      "If you need functions from both plyr and dplyr, please load plyr first, then dplyr:\n",
      "library(plyr); library(dplyr)\n",
      "\n",
      "------------------------------------------------------------------------------\n",
      "\n",
      "\n",
      "Attaching package: ‘plyr’\n",
      "\n",
      "\n",
      "The following objects are masked from ‘package:dplyr’:\n",
      "\n",
      "    arrange, count, desc, failwith, id, mutate, rename, summarise,\n",
      "    summarize\n",
      "\n",
      "\n",
      "The following object is masked from ‘package:purrr’:\n",
      "\n",
      "    compact\n",
      "\n",
      "\n",
      "Loading required package: xfun\n",
      "\n",
      "\n",
      "Attaching package: ‘xfun’\n",
      "\n",
      "\n",
      "The following objects are masked from ‘package:base’:\n",
      "\n",
      "    attr, isFALSE\n",
      "\n",
      "\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "     FATALS         DRUNK_DR     \n",
       " Min.   :1.000   Min.   :0.0000  \n",
       " 1st Qu.:1.000   1st Qu.:0.0000  \n",
       " Median :1.000   Median :0.0000  \n",
       " Mean   :1.085   Mean   :0.2664  \n",
       " 3rd Qu.:1.000   3rd Qu.:1.0000  \n",
       " Max.   :8.000   Max.   :4.0000  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "if (!require('ggplot2')) install.packages('ggplot2'); library('ggplot2')\n",
    "if(!require('Rmisc')) install.packages('Rmisc'); library('Rmisc')\n",
    "if(!require('dplyr')) install.packages('dplyr'); library('dplyr')\n",
    "if(!require('xfun')) install.packages('xfun'); library('xfun')\n",
    "\n",
    "summary(accidentData[c(\"FATALS\",\"DRUNK_DR\")])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1ecae625",
   "metadata": {
    "papermill": {
     "duration": 0.004468,
     "end_time": "2024-01-18T20:05:42.666575",
     "exception": false,
     "start_time": "2024-01-18T20:05:42.662107",
     "status": "completed"
    },
    "tags": []
   },
   "source": [
    "**Observaciones:**\n",
    "\n",
    "- **Número de muertes:** Todos los accidentes recogidos en estos datos reportan una muerte como mínimo. El accidente más grave registró ocho víctimas, y la distribución muestra claramente que la mayoría de los accidentes resultan en una sola muerte.\n",
    "\n",
    "- **Conductores bebidos involucrados en el accidente:** Se analiza con más detalle este dato más adelante para derivar una nueva métrica: Accidentes donde el alcohol está presente o no. En un primer vistazo, la media es de 0.26% de accidentes en los que interviene un conductor bebido. La franja de conductores bebidos por accidente va desde un conductor como mínimo hasta cuatro como máximo."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "06a141b2",
   "metadata": {
    "papermill": {
     "duration": 0.004458,
     "end_time": "2024-01-18T20:05:42.675476",
     "exception": false,
     "start_time": "2024-01-18T20:05:42.671018",
     "status": "completed"
    },
    "tags": []
   },
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "3507bdff",
   "metadata": {
    "papermill": {
     "duration": 0.004569,
     "end_time": "2024-01-18T20:05:42.684673",
     "exception": false,
     "start_time": "2024-01-18T20:05:42.680104",
     "status": "completed"
    },
    "tags": []
   },
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "cc1a67a9",
   "metadata": {
    "papermill": {
     "duration": 0.00439,
     "end_time": "2024-01-18T20:05:42.693511",
     "exception": false,
     "start_time": "2024-01-18T20:05:42.689121",
     "status": "completed"
    },
    "tags": []
   },
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cb0faa65",
   "metadata": {
    "papermill": {
     "duration": 0.004941,
     "end_time": "2024-01-18T20:05:42.702935",
     "exception": false,
     "start_time": "2024-01-18T20:05:42.697994",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6dda7314",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2024-01-18T19:51:46.119920Z",
     "iopub.status.busy": "2024-01-18T19:51:46.117978Z",
     "iopub.status.idle": "2024-01-18T19:51:46.720876Z"
    },
    "papermill": {
     "duration": 0.00444,
     "end_time": "2024-01-18T20:05:42.711885",
     "exception": false,
     "start_time": "2024-01-18T20:05:42.707445",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "none",
   "dataSources": [
    {
     "datasetId": 4297059,
     "sourceId": 7391700,
     "sourceType": "datasetVersion"
    }
   ],
   "dockerImageVersionId": 30618,
   "isGpuEnabled": false,
   "isInternetEnabled": true,
   "language": "r",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "4.0.5"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 21.861677,
   "end_time": "2024-01-18T20:05:42.838476",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2024-01-18T20:05:20.976799",
   "version": "2.5.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
